[tool.poetry]
name = "langchain-project"
version = "0.1.0"
description = ""
authors = ["a <a@a.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.0.137"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
